name: Publish package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@codeoscopic"

      - name: Cache Turborepo
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install packages
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Publish packages
        run: npm run publish
        # Github publish packages event npm run publish fails 🤷‍♂️
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
